name: Security Vulnerability
description: Report a security vulnerability
title: "[Security]: "
labels: "security"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this security vulnerability report!
  - type: textarea
    id: security-vulnerability
    attributes:
      label: Security Vulnerability
      description: Describe the detected security vulnerability here.
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe the impact of this security vulnerability.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce this security vulnerability.
    validations:
      required: false
  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: What type of Operating System are you seeing the problem on?
      placeholder: ex. macOS 14.4.1
    validations:
      required: false
  - type: input
    id: browser
    attributes:
      label: Browser
      description: What type of browser are you seeing the problem on?
      placeholder: ex. Google Chrome Version 123.0.6312.124
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Code to produce this issue.
      description: Please copy and paste any relevant logs/code to re-produce this issue. And the version of the browser you are using. 
      render: shell
